# On part d'une image officielle de Node.js (version 20)
FROM node:20

# On définit le dossier de travail à l'intérieur du conteneur
WORKDIR /app

# On copie les fichiers de configuration des paquets
COPY package*.json ./

# On installe les dépendances
RUN npm install

# On copie tout le reste du code
COPY . .

# On indique que le conteneur utilise le port 3000
EXPOSE 3000

# La commande pour démarrer le serveur
CMD ["node", "server.js"]